// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqhiutfvtkmexdfqfefy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxaGl1dGZ2dGttZXhkZnFmZWZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NDkwODUsImV4cCI6MjA2NzQyNTA4NX0.QQSWCnAxhLEPfqpxmojHcdnG38e8Xb4oBfLXjDhEW9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});